openapi: 3.0.1
info:
  title: Nexus-octo-engine
  version: 0.0.1
servers:
- url: https://virtserver.swaggerhub.com/f0m41h4u7/Nexus-octo-engine/0.0.1
  description: SwaggerHub API Auto Mocking
paths:
  /api/roster:
    post:
      tags:
        - roster
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Roster'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ID'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/roster/{rosterId}:
    put:
      tags:
        - roster
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: rosterId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Roster'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      tags:
        - roster
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: rosterId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    get:
      tags:
        - roster
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: rosterId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roster'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /campaign/{campaignID}/rosters:
    get:
      tags:
        - campaign
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: campaignID
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RosterList'
        '400':
          description: Invalid ID supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /register:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /login:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Token:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    Roster:
      type: object
      properties:
        lore:
          type: string
        name:
          type: string
        supplyLimit:
          type: integer
        supplyUsed:
          type: integer
        availableCP:
          type: integer
        validated:
          type: boolean
    RosterList:
      type: array
      items:
        $ref: '#/components/schemas/Roster'
    ID:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    Advancement:
      type: object
      properties:
        id:
          type: integer
        advType:
          type: string
        descr:
          type: string
        crusCost:
          type: integer
    CampaignAchievements:
      type: object
      properties:
        achievementID:
          type: integer
        campaignID:
          type: integer
        userID:
          type: integer
    CampaignEvent:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        number: 
          type: integer
        player1:
          type: integer
        player2:
          type: integer
        victor:
          type: integer
        lore:
          type: string
    CampaignEvents:
      type: object
      properties:
        eventID:
          type: integer
        campaignID:
          type: integer
    Campaign:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        descr:
          type: string
        isPublic:
          type: boolean
        startingPL:
          type: integer
    CampaignPlayers:
      type: object
      properties:
        userID:
          type: integer
        campaignID:
          type: integer
        u_role:
          type: string
    Detachment:
      type: object
      properties:
        id:
          type: integer
        armyID:
          type: integer
        fraction:
          type: string
        cpCost:
          type: integer
        detachmentType:
          type: string
        powerLevel:
          type: integer
    EventTallies:
      type: object
      properties:
        eventID:
          type: integer
        tallyID: 
          type: string
        unitID:
          type: integer
    Tally:
      type: object
      properties:
        id: 
          type: integer
        tally:
          type: string
        value: 
          type: integer
    UnitGrade:
      type: object
      properties:
        unitID:
          type: integer
        advanceID:
          type: integer
    Unit:
      type: object
      properties:
        id:
          type: integer
        detachmentID:
          type: integer
        name:
          type: string
        unitType:
          type: string
        role:
          type: string
        keywords:
          type: string
        experience:
          type: integer
        crusadePoints:
          type: integer
        powerLevel:
          type: integer
    User:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
security:
  - bearerAuth: []